### ISSUE TITLE
Localization issues after running clean command

### ISSUE THREAD

**Issue by web2style** [mxstbr/react-boilerplate#1191]
First of all, there's an issue with importing `DEFAULT_LOCALE` in `i18n.js`. It should be `import { DEFAULT_LOCALE } from './containers/App/constants';` instead of `import { DEFAULT_LOCALE } from './containers/App/constants';`. The current one thrown an error when running `npm run generate language`. Here is a PR for this: https://github.com/mxstbr/react-boilerplate/pull/1190

After fixing this issue and successfully running `npm run generate language` (let's say it is `da`) we have the following code in the bottom of `i18n.js` file:

```
export const translationMessages = {
  en: formatTranslationMessages('en',
  'da',
 enTranslationMessages),
};
```

but it should be:

```
export const translationMessages = {
  en: formatTranslationMessages('en', enTranslationMessages),
  da: formatTranslationMessages('da', daTranslationMessages),
};
```

Unfortunately I'm not good at regexps, so I can't fix the generator myself (https://github.com/mxstbr/react-boilerplate/blob/master/internals/generators/language/index.js#L48-L53 or https://github.com/mxstbr/react-boilerplate/blob/master/internals/generators/language/format-translation-messages.hbs)

But nevertheless after fixing this issue the localization still doesn't work. After adding appropriate translations to `app/translations/da.json` and changing `DEFAULT_LOCALE` to `da`, I still get English translations rendered in the app. It must be Danish, right? I think @chaintng is the right person to ask this question. There's pretty sure something else I haven't found.

Also, there's an issue with chunked polyfill for browsers without Intl support. So in my case after adding `da` language I got:

```
// Chunked polyfill for browsers without Intl support
    ...
    .then(() => Promise.all([
      System.import('intl/locale-data/jsonp/de.js'),
      System.import('intl/locale-data/jsonp/da.js'),
    ]))
    ...
```

I didn't add `de` language, I think it should be removed after running `npm run clean`.

**Comment by ulrik59** [comment]
After checking, the "real" default language of the app is defined in the `/containers/LanguageProvider/reducer.js`: 

````js
const initialState = fromJS({
  locale: 'en', // this is the line to change
});
````

**Comment by web2style** [comment]
@ulrik59 Yes, the language changes for me if I change `locale`.

So I suppose this should be:

```
import { DEFAULT_LOCALE } from '../App/constants';

const initialState = fromJS({
  locale: DEFAULT_LOCALE
});
```

**Comment by samit4me** [comment]
Can confirm this issue, running the command `npm run generate language` throws errors no matter which locale you use. It also throws errors regardless if you ran `npm run clean` or not, interestingly the errors are different.

Did NOT run `npm run clean`:
```
? [LANGUAGE] What is the language you want to add i18n support for (e.g. "fr", "de")? fr

C:\Users\sam\fresh\react-boilerplate\internals\generators\language\index.js:71
            throw err || stderr;
            ^
Error transforming file: app/containers/LocaleToggle/messages.js
SyntaxError: unknown: [React Intl] `defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.
```

After `npm run clean`:
```
? [LANGUAGE] What is the language you want to add i18n support for (e.g. "fr", "de")? fr
C:\Users\sam\fresh\react-boilerplate\internals\generators\language\index.js:71
            throw err || stderr;
            ^

Error: Command failed: npm run extract-intl
module.js:474
    throw err;
    ^

Error: Cannot find module 'containers/App/constants'
```

I'm unsure exactly where the issue is originating from but I suspect it may or may not be related to [this commit](https://github.com/mxstbr/react-boilerplate/commit/4cb38d9b8bd8e0b228ce9b31e67755393fb3eb0b#diff-297d86e89215543a60a37bcfa91e69c3). I only assume this as it appears to be a fairly large refactor of localization, but I'm only guessing, so please go easy on me if I am wrong.

**Comment by web2style** [comment]
@samit4me The second one is already resolved with #1190.

Yes, the bugs are pretty sure caused by the commit by @chaintng.

**Comment by chaintng** [comment]
Yes, i think it's because of my commit. I'm looking into the langauge generator. Will send a patch soon.

**Comment by chaintng** [comment]
@samit4me for 1), this bug was actually introduced since `v3.1.0`.
Since `LocaleToggle/message.js` are not to be automatically translated.
May be @justingreenberg you want to take a look to this issue.

**Comment by justingreenberg** [comment]
Hi @chaintng just wanted to follow up.. should this be resolved by #1199 and #1200 ?

**Comment by mxstbr** [comment]
Fixed by #1199 as far as I can tell, will release a new version soon!

**Comment by chaintng** [comment]
@justingreenberg 
my pull request doesn't fix the warning 
```
Error transforming file: app/containers/LocaleToggle/messages.js
SyntaxError: unknown: [React Intl] `defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors, also defined as object expressions.
```

Look like because `app/containers/LocaleToggle/messages.js` is not using the pattern same as others. I'm not sure how to fix it properly yet.

**Comment by justingreenberg** [comment]
[`LocaleToggle/messages.js#L13`](https://github.com/mxstbr/react-boilerplate/blob/master/app/containers/LocaleToggle/messages.js#L13) maybe this is the issue....?
```js
export function getLocaleMessages(locales) {
  return locales.reduce((messages, locale) =>
    Object.assign(messages, {
      [locale]: {
        id: `app.components.LocaleToggle.${locale}`, // *** this line?
        defaultMessage: `${locale}`,
      },
    }), {});
}
```

it looks like we are using [a different pattern for translation id](https://github.com/mxstbr/react-boilerplate/blob/master/app/translations/en.json) since this was implemented... so maybe if we change the above to:

```js
//...
id: `boilerplate.containers.LocaleToggle.${locale}`
```

i'm not sure why this would cause a problem (since no conflict) but it's the only thing i can think of

**Comment by chaintng** [comment]
@justingreenberg i think the generator is expecting dump object instead of function
please see also https://github.com/mxstbr/react-boilerplate/issues/1221#issuecomment-260174124

**Comment by Dudelmoser** [comment]
Could this error "`defineMessages()` must be called with an object expression with values that are React Intl Message Descriptors" mean that the translations may not default to an empty string?

**Comment by Dudelmoser** [comment]
I haven't looked into the generator but the generation itself works and I can use the new language afterwards - though I'm still getting runtime errors for missing translations as long as I don't fill the empty strings in /translations.

Both - the error and the possibility to double generate a language - should be fixed though to avoid confusion.
