### ISSUE TITLE
setup does not work

### ISSUE THREAD

**Issue by skskumbharkar** [mxstbr/react-boilerplate#654]
I have used "npm run setup" but I am facing following issue 

> react-boilerplate@3.0.0 setup D:\react-boilerplate
> node ./internals/scripts/setup.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'D:\react-boilerplate\internals\scripts\setup.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3

**Unable to make setup**

**Comment by yookore** [comment]
Can you outline steps you took to get to that point? Maybe a failed git clone?

**Comment by skskumbharkar** [comment]
Git clone is working fine.
I just used "npm run setup".

**Comment by gihrig** [comment]
- I presume your quoted lines in OP confirm `D:\react-boilerplate` is the current dir, but this must be current before `npm run setup.`
- What does `dir .\internals\scripts\setup.js` show you. If it's missing your git clone failed, try again.
- What do `node --version` and `npm --version` show? npm must 3+

**Comment by Andsbf** [comment]
Setup also doesn't work for me.
Details:
``` $ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.1 (15B42)
      Kernel Version: Darwin 15.0.0```

``` $ npm --version
3.9.5```

```$ node --version
v6.2.2```

``` $ git clone git@github.com:mxstbr/react-boilerplate
$ cd react-boilerplate
$  npm run setup

> react-boilerplate@3.0.0 presetup /Users/andsbf/react/react-boilerplate
> npm i chalk

react-boilerplate@3.0.0 /Users/andsbf/react/react-boilerplate
└─┬ chalk@1.1.3
  ├── ansi-styles@2.2.1
  ├── escape-string-regexp@1.0.5
  ├─┬ has-ansi@2.0.0
  │ └── ansi-regex@2.0.0
  ├── strip-ansi@3.0.1
  └── supports-color@2.0.0


> react-boilerplate@3.0.0 setup /Users/andsbf/react/react-boilerplate
> node ./internals/scripts/setup.js


Cleaning old repository ✓
Installing dependencies ✓. (This might take a while)Installing dependencies
Initialising new repository ✓

> react-boilerplate@3.0.0 postsetup /Users/andsbf/react/react-boilerplate
> npm run build:dll


> react-boilerplate@3.0.0 build:dll /Users/andsbf/react/react-boilerplate
> node ./internals/scripts/dependencies.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'shelljs/global'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andsbf/react/react-boilerplate/internals/scripts/dependencies.js:8:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:dll"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 build:dll: `node ./internals/scripts/dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 build:dll script 'node ./internals/scripts/dependencies.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/dependencies.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andsbf/react/react-boilerplate/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 postsetup: `npm run build:dll`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.0.0 postsetup script 'npm run build:dll'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:dll
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andsbf/react/react-boilerplate/npm-debug.log```

```$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-boilerplate@3.0.0~presetup: react-boilerplate@3.0.0
6 verbose lifecycle react-boilerplate@3.0.0~presetup: unsafe-perm in lifecycle true
7 verbose lifecycle react-boilerplate@3.0.0~presetup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andsbf/react/react-boilerplate/node_modules/.bin:/usr/local/bin:/Users/andsbf/.rvm/gems/ruby-2.3.1/bin:/Users/andsbf/.rvm/gems/ruby-2.3.1@global/bin:/Users/andsbf/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/andsbf/go/bin:/Users/andsbf/.rvm/bin
8 verbose lifecycle react-boilerplate@3.0.0~presetup: CWD: /Users/andsbf/react/react-boilerplate
9 silly lifecycle react-boilerplate@3.0.0~presetup: Args: [ '-c', 'npm i chalk' ]
10 silly lifecycle react-boilerplate@3.0.0~presetup: Returned: code: 0  signal: null
11 info lifecycle react-boilerplate@3.0.0~setup: react-boilerplate@3.0.0
12 verbose lifecycle react-boilerplate@3.0.0~setup: unsafe-perm in lifecycle true
13 verbose lifecycle react-boilerplate@3.0.0~setup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andsbf/react/react-boilerplate/node_modules/.bin:/usr/local/bin:/Users/andsbf/.rvm/gems/ruby-2.3.1/bin:/Users/andsbf/.rvm/gems/ruby-2.3.1@global/bin:/Users/andsbf/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/andsbf/go/bin:/Users/andsbf/.rvm/bin
14 verbose lifecycle react-boilerplate@3.0.0~setup: CWD: /Users/andsbf/react/react-boilerplate
15 silly lifecycle react-boilerplate@3.0.0~setup: Args: [ '-c', 'node ./internals/scripts/setup.js' ]
16 silly lifecycle react-boilerplate@3.0.0~setup: Returned: code: 0  signal: null
17 info lifecycle react-boilerplate@3.0.0~postsetup: react-boilerplate@3.0.0
18 verbose lifecycle react-boilerplate@3.0.0~postsetup: unsafe-perm in lifecycle true
19 verbose lifecycle react-boilerplate@3.0.0~postsetup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andsbf/react/react-boilerplate/node_modules/.bin:/usr/local/bin:/Users/andsbf/.rvm/gems/ruby-2.3.1/bin:/Users/andsbf/.rvm/gems/ruby-2.3.1@global/bin:/Users/andsbf/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/andsbf/go/bin:/Users/andsbf/.rvm/bin
20 verbose lifecycle react-boilerplate@3.0.0~postsetup: CWD: /Users/andsbf/react/react-boilerplate
21 silly lifecycle react-boilerplate@3.0.0~postsetup: Args: [ '-c', 'npm run build:dll' ]
22 silly lifecycle react-boilerplate@3.0.0~postsetup: Returned: code: 1  signal: null
23 info lifecycle react-boilerplate@3.0.0~postsetup: Failed to exec postsetup script
24 verbose stack Error: react-boilerplate@3.0.0 postsetup: `npm run build:dll`
24 verbose stack Exit status 1
24 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
24 verbose stack     at emitTwo (events.js:106:13)
24 verbose stack     at EventEmitter.emit (events.js:191:7)
24 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
24 verbose stack     at emitTwo (events.js:106:13)
24 verbose stack     at ChildProcess.emit (events.js:191:7)
24 verbose stack     at maybeClose (internal/child_process.js:852:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
25 verbose pkgid react-boilerplate@3.0.0
26 verbose cwd /Users/andsbf/react/react-boilerplate
27 error Darwin 15.0.0
28 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
29 error node v6.2.2
30 error npm  v3.9.5
31 error code ELIFECYCLE
32 error react-boilerplate@3.0.0 postsetup: `npm run build:dll`
32 error Exit status 1
33 error Failed at the react-boilerplate@3.0.0 postsetup script 'npm run build:dll'.
33 error Make sure you have the latest version of node.js and npm installed.
33 error If you do, this is most likely a problem with the react-boilerplate package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error     npm run build:dll
33 error You can get information on how to open an issue for this project with:
33 error     npm bugs react-boilerplate
33 error Or if that isn't available, you can get their info via:
33 error     npm owner ls react-boilerplate
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]```

Please let me know anything else I can attach here that might help. I'm completely new to react so I'm sorry if I miss something here.

**Comment by Andsbf** [comment]
I believe this might be related:

https://github.com/mxstbr/react-boilerplate/issues/658

But I still don't know how to fix it.

**Comment by gihrig** [comment]
Seems likely related to #658. That has been resolved (AFAIK).

Please clone a new copy and try again.

Sorry for the problems...

**Comment by Andsbf** [comment]
Problem solved here! thanks!

**Comment by andreyluiz** [comment]
I am still getting the shelljs/global error. Even cloning fresh and new.

**Comment by gihrig** [comment]
@andreyluiz are you running an npm > 3? `npm --version`
Have you tried `npm cache clean`?

Then a new clone and `npm run setup`?

If that doesn't work please give us a screen capture of your `npm run setup` result.

**Comment by skskumbharkar** [comment]
I just removed my all installed node_modules.
And then used "npm run setup".
It is working fine now.
We need npm > 3  npm --version

**Comment by chris-kobrzak** [comment]
Had an identical issue as @Andsbf and it's definitely been caused by an outdated NPM package. When I upgraded `npm` from version 2.14.12 to 3.10.5 the installer started working again.
