### ISSUE TITLE
Error while running npm run generate container

### ISSUE THREAD

**Issue by LokiMasterMind** [mxstbr/react-boilerplate#739]
Hi ,

any one knows what was the issue ???

Error : 

![image](https://cloud.githubusercontent.com/assets/15119623/16911852/8081cde8-4cfe-11e6-9627-fa5f54530b4d.png)

Thanks

**Comment by gihrig** [comment]
@LokiMasterMind This is kind of a lame shot-in-the-dark solution, but I just pushed a dependency roll-up update. #748 

Clone a new react-boilerplate and try again?

I did try the generators as part the roll-up testing process, no problems.

`Mac OS 10.11.5`
`npm 3.8.2`
`node 5.8.0`

**Comment by mxstbr** [comment]
Works for me on macOS 10.12 too. Are you on Windows by chance?

![screen shot 2016-07-19 at 09 34 21](https://cloud.githubusercontent.com/assets/7525670/16942028/032df95c-4d94-11e6-9681-dd5ba52892f4.png)

**Comment by LokiMasterMind** [comment]
@gihrig  
I had clone latest copy of repo but still getting this error. 

@mxstbr 
Yes, I am using Windows 10 OS
npm 3.10.5
node 5.5.0

**Comment by mxstbr** [comment]
@jwinn could you investigate this? That'd be great!

**Comment by jwinn** [comment]
@mxstbr @LokiMasterMind Just looking at the error message, `rx-lite` is throwing an error on a poorly formed regex `/.{1,0}/`. Before I check in windows whether the bp works or not, can we determine if this is caused by `rx-lite` which is not in the bp?

**Comment by mxstbr** [comment]
Seems to be used by `inquirer`, which is used by `plop` which we use for the command line stuff.

**Comment by jwinn** [comment]
I am able to run this on Windows 10 _successfully_

**Steps I took**

```
{lamb} git clone https://github.com/mxstbr/react-boilerplate
Cloning into 'react-boilerplate'...
remote: Counting objects: 5655, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 5655 (delta 5), reused 0 (delta 0), pack-reused 5642R
Receiving objects: 100% (5655/5655), 2.71 MiB | 926.00 KiB/s, done.
Resolving deltas: 100% (3168/3168), done.
Checking connectivity... done.
```

```
{lamb} npm run setup

> react-boilerplate@3.0.0 presetup C:\Users\jwinn\react-boilerplate
> npm i chalk

react-boilerplate@3.0.0 C:\Users\jwinn\react-boilerplate
`-- chalk@1.1.3
  +-- ansi-styles@2.2.1
  +-- escape-string-regexp@1.0.5
  +-- has-ansi@2.0.0
  | `-- ansi-regex@2.0.0
  +-- strip-ansi@3.0.1
  `-- supports-color@2.0.0


> react-boilerplate@3.0.0 setup C:\Users\jwinn\react-boilerplate
> node ./internals/scripts/setup.js


Cleaning old repository ✓
Installing dependencies ✓. (This might take a while)Installing dependencies
Initialising new repository.. ✓
Done!
> react-boilerplate@3.0.0 postsetup C:\Users\jwinn\react-boilerplate
> npm run build:dll


> react-boilerplate@3.0.0 build:dll C:\Users\jwinn\react-boilerplate
> node ./internals/scripts/dependencies.js

Building the Webpack DLL...
Hash: c6bac94a1fc59def283b
Version: webpack 2.1.0-beta.15
Time: 3999ms
                      Asset     Size  Chunks             Chunk Names
reactBoilerplateDeps.dll.js  2.26 MB       0  [emitted]  reactBoilerplateDeps
chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 2.01 MB [rendered]
  [633] dll reactBoilerplateDeps 12 bytes {0} [built]
     + 633 hidden modules
```

```
{lamb} npm run generate container

> react-boilerplate@3.0.0 generate C:\Users\jwinn\react-boilerplate
> plop --plopfile internals/generators/index.js "container"

? [CONTAINER] What should it be called? Form
? [CONTAINER] Do you want headers? No
? [CONTAINER] Does it have styling? No
? [CONTAINER] Do you want an actions/constants/selectors/reducer tupel for this container? Yes
? [CONTAINER] Do you want sagas for asynchronous flows? (e.g. fetching data) Yes
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\index.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\tests\index.test.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\actions.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\tests\actions.test.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\constants.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\selectors.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\tests\selectors.test.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\reducer.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\tests\reducer.test.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\sagas.js
[SUCCESS] add C:\Users\jwinn\react-boilerplate\app\containers\Form\tests\sagas.test.js
```

**System Info** (Running with ConEmu/Cmder)

```
{lamb} systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586
System Type:               x64-based PC

{lamb} where git && git --version
C:\tools\cmder\vendor\msysgit\bin\git.exe
C:\tools\cmder\vendor\msysgit\cmd\git.exe
C:\Program Files\Git\cmd\git.exe
git version 1.9.4.msysgit.0

{lamb} where node && node --version && where npm && npm --version
C:\Program Files\nodejs\node.exe
v6.3.0
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
3.10.3
```

**Comment by mxstbr** [comment]
Thanks so much @jwinn!

So, this means it's definitely something related to your environment then @LokiMasterMind. Sorry we can't help you more!

**Comment by LokiMasterMind** [comment]
@gihrig @mxstbr  Thanks for your support and quick reply.

I was using Git Bash on Windows10  and it shows this error, after switched to windows CMD its work 

had some research on google and found its due to cli settings.
	
> Set a default cli width of 80 characters
> In some environment, `cli-width` is known to return a default value of
> `0`, which causes inquirer to crash in such a context.
  
but this doesn't work..

Don't know why this is happen with git bash but i am happy finally its works on my machine.

**Comment by gihrig** [comment]
@LokiMasterMind Thanks for reporting back. Maybe it will help someone.
