### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by Mangirdaz** [mxstbr/react-boilerplate#754]
```
root@mj react-boilerplate]# npm run setup

> react-boilerplate@3.0.0 presetup /home/mangis/workspace/react-boilerplate
> npm i chalk

chalk@1.1.3 node_modules/chalk

> react-boilerplate@3.0.0 setup /home/mangis/workspace/react-boilerplate
> node ./internals/scripts/setup.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/mangis/workspace/react-boilerplate/internals/scripts/setup.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 4.5.7-202.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "setup"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 setup script 'node ./internals/scripts/setup.js'.
npm ERR! This is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mangis/workspace/react-boilerplate/npm-debug.log
```

cat /home/mangis/workspace/react-boilerplate/npm-debug.log >>
https://gist.github.com/Mangirdaz/b2ad8666e8637ef7b70fc2f6453b4615

**Comment by rog** [comment]
You need at least `npm 3` and you have `npm v2.15.8`

**Comment by Mangirdaz** [comment]
sorry, debug output:
```
[root@mj react-boilerplate]# npm install npm -g
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/lib
└── npm@3.10.5 
```

https://gist.github.com/Mangirdaz/19a5bd702105135e35c4902d902dbc07

Looks like some dependencies is not satisfied with install (new to npm, will check)

**Comment by Mangirdaz** [comment]
looks like these could be an issue on my fedora:
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
`

**Comment by rog** [comment]
Try removing the `node_modules` folder and try `npm install` again.

The error you have now is similar to this #725

**Comment by Mangirdaz** [comment]
same :/ 

`[root@mj react-boilerplate]# cat /home/mangis/workspace/react-boilerplate/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'setup' ]
2 info using npm@3.10.5
3 info using node@v4.4.7
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-boilerplate@3.0.0~presetup: react-boilerplate@3.0.0
6 verbose lifecycle react-boilerplate@3.0.0~presetup: unsafe-perm in lifecycle true
7 verbose lifecycle react-boilerplate@3.0.0~presetup: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mangis/workspace/react-boilerplate/node_modules/.bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin
8 verbose lifecycle react-boilerplate@3.0.0~presetup: CWD: /home/mangis/workspace/react-boilerplate
9 silly lifecycle react-boilerplate@3.0.0~presetup: Args: [ '-c', 'npm i chalk' ]
10 silly lifecycle react-boilerplate@3.0.0~presetup: Returned: code: 0  signal: null
11 info lifecycle react-boilerplate@3.0.0~setup: react-boilerplate@3.0.0
12 verbose lifecycle react-boilerplate@3.0.0~setup: unsafe-perm in lifecycle true
13 verbose lifecycle react-boilerplate@3.0.0~setup: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mangis/workspace/react-boilerplate/node_modules/.bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin
14 verbose lifecycle react-boilerplate@3.0.0~setup: CWD: /home/mangis/workspace/react-boilerplate
15 silly lifecycle react-boilerplate@3.0.0~setup: Args: [ '-c', 'node ./internals/scripts/setup.js' ]
16 silly lifecycle react-boilerplate@3.0.0~setup: Returned: code: 1  signal: null
17 info lifecycle react-boilerplate@3.0.0~setup: Failed to exec setup script
18 verbose stack Error: react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at EventEmitter.emit (events.js:172:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:87:13)
18 verbose stack     at ChildProcess.emit (events.js:172:7)
18 verbose stack     at maybeClose (internal/child_process.js:827:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
19 verbose pkgid react-boilerplate@3.0.0
20 verbose cwd /home/mangis/workspace/react-boilerplate
21 error Linux 4.5.7-202.fc23.x86_64
22 error argv "/usr/bin/node" "/bin/npm" "run" "setup"
23 error node v4.4.7
24 error npm  v3.10.5
25 error code ELIFECYCLE
26 error react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
26 error Exit status 1
27 error Failed at the react-boilerplate@3.0.0 setup script 'node ./internals/scripts/setup.js'.
`

**Comment by gihrig** [comment]
It is safe to ignore `WARN` messages, they are not a significant problem, in general development and specifically in this case. @rog is correct, you must have npm 3+.

@Mangirdaz you should be good to go now. I'm closing this issue as it is resolved. If you have additional problems please open an new issue.

**Comment by Mangirdaz** [comment]
I still get same error but now stuff starts. If this is acceptable from your point of view we can close. thanks

**Comment by mxstbr** [comment]
It's not an error, it's a `WARN`ing, which is, in fact, expected.

**Comment by Mangirdaz** [comment]
Ok :) Just as per my understanding ERR mean error :D stuff works, but this is output I get each time
```
> react-boilerplate@3.0.0 setup /home/mangis/workspace/react-boilerplate
> node ./internals/scripts/setup.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/mangis/workspace/react-boilerplate/internals/scripts/setup.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Linux 4.5.7-202.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "setup"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.0.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.0.0 setup script 'node ./internals/scripts/setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./internals/scripts/setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mangis/workspace/react-boilerplate/npm-debug.log
[root@mj react-boilerplate]# npm run setup

> react-boilerplate@3.0.0 presetup /home/mangis/workspace/react-boilerplate
> npm i chalk

```

**Comment by mxstbr** [comment]
Right, that's because you've already run `npm run setup` – that's only mean to be ran a single time. If you take a look at the error message:

```
Cannot find module '/home/mangis/workspace/react-boilerplate/internals/scripts/setup.js'
```

Which means that the setup script is deleted because you've ran setup already!

**Comment by Mangirdaz** [comment]
k, Thanks :) I think this either should be notes in docs or make resilient for multiple runs (I dont know why but it gave me same error for the first time too, but this does not matters now as stuff works) ,

Thanks

**Comment by mxstbr** [comment]
It is noted in the docs. https://github.com/mxstbr/react-boilerplate/blob/master/docs/general/commands.md#initialization

<img width="1208" alt="screen shot 2016-07-20 at 10 48 03" src="https://cloud.githubusercontent.com/assets/7525670/16980670/7541ba14-4e67-11e6-99e1-5d212e8dc37c.png">

**Comment by Mangirdaz** [comment]
:) Ok, my bad :D just looked first page and went straight to debug mode :)

**Comment by richb-hanover** [comment]
I was just about to submit a report on this, but fortunately, I searched first...

I had a potential failure during the initial `npm run setup` (I use OSX, Little Snitch that catches and blocks suspicious connections.) I started the setup and left my computer for ~15 minutes. When I returned, LittleSnitch had asked "Did you want to connect...?" and the setup was paused. 

I clicked OK, and setup seemed to complete without complaint. But since I was unsure if that might have perturbed the installation, I said, "Oh heck. Let's just run the setup again." And I got the error.

Proposals: 

1. Don't worry about this. (I simply re-cloned the repo, and sat with the setup process running the second time.)
2. Detect the missing setup.js file and have the setup script mention that this could happen if it has been run twice.
3. Do something fancy with error recovery, etc. :-)

My preference would be 2 & 1 - mention that missing setup script could be due to running twice, and recommend that people re-clone the repo (since that's usually fast, and foolproof.)

**Comment by mxstbr** [comment]
Yeah, I guess that'd be nice @richb-hanover! PR maybe?

**Comment by gihrig** [comment]
I opened #760 as a discussion addressing the need for improved setup UX. Can we move this discussion there?

**Comment by richb-hanover** [comment]
@gihrig @mxstbr Yes, please feel free to close this issue and move the discussion elsewhere. I am totally content - the only reason for my initial post was to report the problem in the spirit of, "We promise not to fix it if we don't know it's broke."

You all seem to have this well in hand, so I will quietly drop out of sight :-)
