### ISSUE TITLE
Tests fail in minimal example app after npm run clean

### ISSUE THREAD

**Issue by gihrig** [mxstbr/react-boilerplate#865]
Repro steps:
Note: wait for #862 to land. Other eslint errors will abort before these can run.
`npm run setup`
`npm run clean`
`npm run test`

```
ERROR in ./app/tests/store.test.js
Module not found: Error: Can't resolve './store' in '/Users/glen/Documents/JavaScript/Research/react-bp2/app/tests'
 @ ./app/tests/store.test.js 18:209-227
```

The error is a result of the templates dir structure not matching that of the boilerplate App. The immediate issue is addressed in #863, specifically [#863 (note)](https://github.com/mxstbr/react-boilerplate/pull/863/files#diff-46c47e6183968ac4496ee7740147bc2bL3)

*.test.js files are grouped under `/templates` directory. `npm run clean` copies these files to `/tests` directory in the minimal example project created by the clean command.

This creates an issue where the path to the tested component varies between `templates` and `tests`. 

This results in a bug where tests fail after `clean` because the tested component does not resolve.

**Comment by uzarubin** [comment]
It looks like this has been resolved already. No?

**Comment by gihrig** [comment]
@uzarubin Yes closed by #863.

Thanks for brining this up 👍

**Comment by gihrig** [comment]
@uzarubin I was mistaken. This issue is _not_ fixed, only worked around.

The problem is as stated in the OP. The directory structure in templates does not match the generated structure.

My bad 😢

**Comment by uzarubin** [comment]
@gihrig no worries. I was just looking over issues to see which ones were resolved. I'll try to look into this one sometime tomorrow.

**Comment by mxstbr** [comment]
Is this still an issue?

**Comment by gihrig** [comment]
Yes this is still an issue. 

 `internals/templates/*` files are moved to various locations by the clean script. `store.test.js` in particular has eslint disabled [here](https://github.com/mxstbr/react-boilerplate/blob/master/internals/templates/store.test.js#L6) becuase the templates dir structure does not match the generated dir structure. This is the root cause for this issue, the eslint disable is a work around.

It has been agreed [here](https://github.com/mxstbr/react-boilerplate/pull/863#issuecomment-239659433) that `internals/templates/` structure should match the destination structure. This requires reworking [`internals/scripts/clean.js`](https://github.com/mxstbr/react-boilerplate/blob/master/internals/scripts/clean.js#L24-L29) as well.

**Comment by gihrig** [comment]
Thoroughly fixed by @outdooricon in #1414 🎉
