### ISSUE TITLE
npm run setup not working

### ISSUE THREAD

**Issue by pavel06081991** [mxstbr/react-boilerplate#872]
1 hour ago when I created a fork of this repository npm run setup worked, but npm run clean did not work. Now after some bug fixing from your side I made new fork to test npm run clean, but now even npm run setup does not work. Here are the error.
```
> node ./internals/scripts/setup.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by gihrig** [comment]
ShellJs is loaded through `package.json`. Can you check your `node_modules` folder to see if it's there?
You should have something like 1182 nodules in `node_modules`. If not try:

1. Delete `node_modules` folder
2. Run `npm cache clean`
3. Run `npm install`

If you're still having problems, please post the contents of `npm-debug.log`

**Comment by mxstbr** [comment]
Absolutely my bad, this was a regression introduced by merging @Dattaya's #860!

Fixed on `master` for now by reverting #860, @Dattaya would you mind looking into this a bit more?

**Comment by mxstbr** [comment]
Wow you were fast @gihrig! 👏

This is an issue with the script because we use `shelljs` before we've run `npm install` which means `shelljs` doesn't exist yet! Need to find a better solution for #860…

**Comment by gazpachu** [comment]
I've just downloaded the boilerplate and I still have this error

**Comment by gihrig** [comment]
@gazpachu You're seeing `Error: Cannot find module 'shelljs'`?

Did you try the solution presented [above](https://github.com/mxstbr/react-boilerplate/issues/872#issuecomment-239930748)?

If so, please give us more data on version of npm, Mac OS, the commands you're running and the full error you're getting.

I just confirmed a successful clone and setup with

`npm -v 3.10.5`
`node -v v6.3.1`
OS X 10.11.6

And then also successful with

`npm -v 3.10.6`
`node -v v6.4.0`
OS X 10.11.6

**Comment by gazpachu** [comment]
The issue was with the update script. No problem with shelljs. Anyway, the app was starting fine even with the error in the setup.
